### ISSUE TITLE
Не компилируется на Linux

### ISSUE THREAD

**Issue by dmitriytpt** [DesmondFox/GameOfLife#1]
Игра не собирается компилятором GCC 7.1.1
Ошибки выдаваемые компилятором:
`/usr/bin/ld: cannot find -lQt5Widgets
/usr/bin/ld: cannot find -lQt5Gui
/usr/bin/ld: cannot find -lQt5Core
/usr/bin/ld: cannot find -lGL
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
make: *** [Makefile:200: GameOfLife] Ошибка 1`
Пакет Qt5 установлен.

**Comment by dmitriytpt** [comment]
8f061835b292d6c1deaad9cbeaea253d8f1992c8 решил проблему. Теперь все собирается.

**Comment by DesmondFox** [comment]
Проблема была в строчке файла GameOfLife.pro

`QMAKE_LFLAGS_RELEASE += -static -static-libgcc`

Исправлено
