### ISSUE TITLE
Не работает кнопка "Настройки"

### ISSUE THREAD

**Issue by dmitriytpt** [DesmondFox/GameOfLife#2]
Компилятор GCC 7.1.1, Linux
При работе с приложением нажатие кнопки "Настройки" не обрабатывается.

**Comment by DesmondFox** [comment]
Потому что не реализовано. Но в планах. Пока надо довести до ума алгоритм

**Comment by dmitriytpt** [comment]
e35523700f624948722b1b85988b27edbbe2a81f добавил обработку. Осталось доделать функиционал кнопки.

**Comment by dmitriytpt** [comment]
49a0ddd5570557458dbe3e986db0e848d8945b57
![default](https://user-images.githubusercontent.com/22558815/28436301-22719356-6d9f-11e7-8319-45f82b9372ba.png)
Несмотря на то, что реализация настроек документирована, они до сих пустуют.
Операционная система - Linux. Компилятор - GCC 7.1.1. Qt - qt5-base 5.9.1

**Comment by DesmondFox** [comment]
Странно, у меня таких проблем нет. Нормально склонировало репозиторий и все кнопки есть и работают

**Comment by dmitriytpt** [comment]
Вы сказали:
> Нормально склонировало репозиторий

Хочу заметить, что мой локальный репозиторий полностью обновлен, поэтому проблемы скорее всего в исходниках и в особенностях моей ОС *(Arch Linux на ядре linux-zen)*.

**Comment by dmitriytpt** [comment]
455fa3976e760cd89f47e6f79a34ad2a33f45143 все исправил (Операционная система и компилятор те-же). 
![default](https://user-images.githubusercontent.com/22558815/28474766-76f10b6a-6e52-11e7-9c0f-f0f616bcf291.png)
